# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: catalog.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rcatalog.proto\"#\n\x0cQueryRequest\x12\x13\n\x0bproductName\x18\x01 \x01(\t\"f\n\rQueryResponse\x12\x13\n\x0bproductName\x18\x01 \x01(\t\x12\x12\n\x05price\x18\x02 \x01(\x02H\x00\x88\x01\x01\x12\x15\n\x08quantity\x18\x03 \x01(\x05H\x01\x88\x01\x01\x42\x08\n\x06_priceB\x0b\n\t_quantity\"H\n\rUpdateRequest\x12\x13\n\x0bproductName\x18\x01 \x01(\t\x12\x15\n\x08quantity\x18\x02 \x01(\x05H\x00\x88\x01\x01\x42\x0b\n\t_quantity\"\"\n\x0eUpdateResponse\x12\x10\n\x08response\x18\x01 \x01(\x05\x32`\n\x07\x43\x61talog\x12(\n\x05Query\x12\r.QueryRequest\x1a\x0e.QueryResponse\"\x00\x12+\n\x06Update\x12\x0e.UpdateRequest\x1a\x0f.UpdateResponse\"\x00\x62\x06proto3')



_QUERYREQUEST = DESCRIPTOR.message_types_by_name['QueryRequest']
_QUERYRESPONSE = DESCRIPTOR.message_types_by_name['QueryResponse']
_UPDATEREQUEST = DESCRIPTOR.message_types_by_name['UpdateRequest']
_UPDATERESPONSE = DESCRIPTOR.message_types_by_name['UpdateResponse']
QueryRequest = _reflection.GeneratedProtocolMessageType('QueryRequest', (_message.Message,), {
  'DESCRIPTOR' : _QUERYREQUEST,
  '__module__' : 'catalog_pb2'
  # @@protoc_insertion_point(class_scope:QueryRequest)
  })
_sym_db.RegisterMessage(QueryRequest)

QueryResponse = _reflection.GeneratedProtocolMessageType('QueryResponse', (_message.Message,), {
  'DESCRIPTOR' : _QUERYRESPONSE,
  '__module__' : 'catalog_pb2'
  # @@protoc_insertion_point(class_scope:QueryResponse)
  })
_sym_db.RegisterMessage(QueryResponse)

UpdateRequest = _reflection.GeneratedProtocolMessageType('UpdateRequest', (_message.Message,), {
  'DESCRIPTOR' : _UPDATEREQUEST,
  '__module__' : 'catalog_pb2'
  # @@protoc_insertion_point(class_scope:UpdateRequest)
  })
_sym_db.RegisterMessage(UpdateRequest)

UpdateResponse = _reflection.GeneratedProtocolMessageType('UpdateResponse', (_message.Message,), {
  'DESCRIPTOR' : _UPDATERESPONSE,
  '__module__' : 'catalog_pb2'
  # @@protoc_insertion_point(class_scope:UpdateResponse)
  })
_sym_db.RegisterMessage(UpdateResponse)

_CATALOG = DESCRIPTOR.services_by_name['Catalog']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _QUERYREQUEST._serialized_start=17
  _QUERYREQUEST._serialized_end=52
  _QUERYRESPONSE._serialized_start=54
  _QUERYRESPONSE._serialized_end=156
  _UPDATEREQUEST._serialized_start=158
  _UPDATEREQUEST._serialized_end=230
  _UPDATERESPONSE._serialized_start=232
  _UPDATERESPONSE._serialized_end=266
  _CATALOG._serialized_start=268
  _CATALOG._serialized_end=364
# @@protoc_insertion_point(module_scope)
