# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import order_pb2 as order__pb2


class OrderStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Buy = channel.unary_unary(
                '/Order/Buy',
                request_serializer=order__pb2.BuyRequest.SerializeToString,
                response_deserializer=order__pb2.BuyResponse.FromString,
                )
        self.OrderQuery = channel.unary_unary(
                '/Order/OrderQuery',
                request_serializer=order__pb2.OrderQueryRequest.SerializeToString,
                response_deserializer=order__pb2.OrderQueryResponse.FromString,
                )
        self.HealthCheck = channel.unary_unary(
                '/Order/HealthCheck',
                request_serializer=order__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=order__pb2.HealthCheckResponse.FromString,
                )
        self.Notify = channel.unary_unary(
                '/Order/Notify',
                request_serializer=order__pb2.NotifyRequest.SerializeToString,
                response_deserializer=order__pb2.NotifyResponse.FromString,
                )
        self.Sync = channel.unary_stream(
                '/Order/Sync',
                request_serializer=order__pb2.SyncRequest.SerializeToString,
                response_deserializer=order__pb2.SyncResponse.FromString,
                )


class OrderServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Buy(self, request, context):
        """Define RPC to execute buy from catalog and return order_id
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def OrderQuery(self, request, context):
        """Define RPC to query orders
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Define RPC for health check
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Notify(self, request, context):
        """Define RPC for notifying non-leader order services
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Sync(self, request, context):
        """Sync request
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OrderServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Buy': grpc.unary_unary_rpc_method_handler(
                    servicer.Buy,
                    request_deserializer=order__pb2.BuyRequest.FromString,
                    response_serializer=order__pb2.BuyResponse.SerializeToString,
            ),
            'OrderQuery': grpc.unary_unary_rpc_method_handler(
                    servicer.OrderQuery,
                    request_deserializer=order__pb2.OrderQueryRequest.FromString,
                    response_serializer=order__pb2.OrderQueryResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=order__pb2.HealthCheckRequest.FromString,
                    response_serializer=order__pb2.HealthCheckResponse.SerializeToString,
            ),
            'Notify': grpc.unary_unary_rpc_method_handler(
                    servicer.Notify,
                    request_deserializer=order__pb2.NotifyRequest.FromString,
                    response_serializer=order__pb2.NotifyResponse.SerializeToString,
            ),
            'Sync': grpc.unary_stream_rpc_method_handler(
                    servicer.Sync,
                    request_deserializer=order__pb2.SyncRequest.FromString,
                    response_serializer=order__pb2.SyncResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Order', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Order(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Buy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Order/Buy',
            order__pb2.BuyRequest.SerializeToString,
            order__pb2.BuyResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def OrderQuery(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Order/OrderQuery',
            order__pb2.OrderQueryRequest.SerializeToString,
            order__pb2.OrderQueryResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Order/HealthCheck',
            order__pb2.HealthCheckRequest.SerializeToString,
            order__pb2.HealthCheckResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Notify(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Order/Notify',
            order__pb2.NotifyRequest.SerializeToString,
            order__pb2.NotifyResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Sync(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/Order/Sync',
            order__pb2.SyncRequest.SerializeToString,
            order__pb2.SyncResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
