# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: order.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0border.proto\"E\n\nBuyRequest\x12\x13\n\x0bproductName\x18\x01 \x01(\t\x12\x15\n\x08quantity\x18\x02 \x01(\x05H\x00\x88\x01\x01\x42\x0b\n\t_quantity\"7\n\x0b\x42uyResponse\x12\x18\n\x0borderNumber\x18\x01 \x01(\x02H\x00\x88\x01\x01\x42\x0e\n\x0c_orderNumber\"(\n\x11OrderQueryRequest\x12\x13\n\x0borderNumber\x18\x01 \x01(\t\"{\n\x12OrderQueryResponse\x12\x13\n\x0borderNumber\x18\x01 \x01(\t\x12\x18\n\x0bproductName\x18\x02 \x01(\tH\x00\x88\x01\x01\x12\x17\n\nproductQty\x18\x03 \x01(\x05H\x01\x88\x01\x01\x42\x0e\n\x0c_productNameB\r\n\x0b_productQty\")\n\x12HealthCheckRequest\x12\x13\n\x0bhealthCheck\x18\x01 \x01(\x05\"&\n\x13HealthCheckResponse\x12\x0f\n\x07healthy\x18\x01 \x01(\x05\"\x1f\n\rNotifyRequest\x12\x0e\n\x06leader\x18\x01 \x01(\t\"\"\n\x0eNotifyResponse\x12\x10\n\x08response\x18\x01 \x01(\t\"t\n\x0bSyncRequest\x12\x13\n\x0borderNumber\x18\x01 \x01(\t\x12\x18\n\x0bproductName\x18\x02 \x01(\tH\x00\x88\x01\x01\x12\x17\n\nproductQty\x18\x03 \x01(\x05H\x01\x88\x01\x01\x42\x0e\n\x0c_productNameB\r\n\x0b_productQty\"\x9c\x01\n\x0cSyncResponse\x12\x10\n\x08response\x18\x01 \x01(\t\x12\x18\n\x0borderNumber\x18\x02 \x01(\tH\x00\x88\x01\x01\x12\x18\n\x0bproductName\x18\x03 \x01(\tH\x01\x88\x01\x01\x12\x17\n\nproductQty\x18\x04 \x01(\x05H\x02\x88\x01\x01\x42\x0e\n\x0c_orderNumberB\x0e\n\x0c_productNameB\r\n\x0b_productQty2\xf6\x01\n\x05Order\x12\"\n\x03\x42uy\x12\x0b.BuyRequest\x1a\x0c.BuyResponse\"\x00\x12\x37\n\nOrderQuery\x12\x12.OrderQueryRequest\x1a\x13.OrderQueryResponse\"\x00\x12:\n\x0bHealthCheck\x12\x13.HealthCheckRequest\x1a\x14.HealthCheckResponse\"\x00\x12+\n\x06Notify\x12\x0e.NotifyRequest\x1a\x0f.NotifyResponse\"\x00\x12\'\n\x04Sync\x12\x0c.SyncRequest\x1a\r.SyncResponse\"\x00\x30\x01\x62\x06proto3')



_BUYREQUEST = DESCRIPTOR.message_types_by_name['BuyRequest']
_BUYRESPONSE = DESCRIPTOR.message_types_by_name['BuyResponse']
_ORDERQUERYREQUEST = DESCRIPTOR.message_types_by_name['OrderQueryRequest']
_ORDERQUERYRESPONSE = DESCRIPTOR.message_types_by_name['OrderQueryResponse']
_HEALTHCHECKREQUEST = DESCRIPTOR.message_types_by_name['HealthCheckRequest']
_HEALTHCHECKRESPONSE = DESCRIPTOR.message_types_by_name['HealthCheckResponse']
_NOTIFYREQUEST = DESCRIPTOR.message_types_by_name['NotifyRequest']
_NOTIFYRESPONSE = DESCRIPTOR.message_types_by_name['NotifyResponse']
_SYNCREQUEST = DESCRIPTOR.message_types_by_name['SyncRequest']
_SYNCRESPONSE = DESCRIPTOR.message_types_by_name['SyncResponse']
BuyRequest = _reflection.GeneratedProtocolMessageType('BuyRequest', (_message.Message,), {
  'DESCRIPTOR' : _BUYREQUEST,
  '__module__' : 'order_pb2'
  # @@protoc_insertion_point(class_scope:BuyRequest)
  })
_sym_db.RegisterMessage(BuyRequest)

BuyResponse = _reflection.GeneratedProtocolMessageType('BuyResponse', (_message.Message,), {
  'DESCRIPTOR' : _BUYRESPONSE,
  '__module__' : 'order_pb2'
  # @@protoc_insertion_point(class_scope:BuyResponse)
  })
_sym_db.RegisterMessage(BuyResponse)

OrderQueryRequest = _reflection.GeneratedProtocolMessageType('OrderQueryRequest', (_message.Message,), {
  'DESCRIPTOR' : _ORDERQUERYREQUEST,
  '__module__' : 'order_pb2'
  # @@protoc_insertion_point(class_scope:OrderQueryRequest)
  })
_sym_db.RegisterMessage(OrderQueryRequest)

OrderQueryResponse = _reflection.GeneratedProtocolMessageType('OrderQueryResponse', (_message.Message,), {
  'DESCRIPTOR' : _ORDERQUERYRESPONSE,
  '__module__' : 'order_pb2'
  # @@protoc_insertion_point(class_scope:OrderQueryResponse)
  })
_sym_db.RegisterMessage(OrderQueryResponse)

HealthCheckRequest = _reflection.GeneratedProtocolMessageType('HealthCheckRequest', (_message.Message,), {
  'DESCRIPTOR' : _HEALTHCHECKREQUEST,
  '__module__' : 'order_pb2'
  # @@protoc_insertion_point(class_scope:HealthCheckRequest)
  })
_sym_db.RegisterMessage(HealthCheckRequest)

HealthCheckResponse = _reflection.GeneratedProtocolMessageType('HealthCheckResponse', (_message.Message,), {
  'DESCRIPTOR' : _HEALTHCHECKRESPONSE,
  '__module__' : 'order_pb2'
  # @@protoc_insertion_point(class_scope:HealthCheckResponse)
  })
_sym_db.RegisterMessage(HealthCheckResponse)

NotifyRequest = _reflection.GeneratedProtocolMessageType('NotifyRequest', (_message.Message,), {
  'DESCRIPTOR' : _NOTIFYREQUEST,
  '__module__' : 'order_pb2'
  # @@protoc_insertion_point(class_scope:NotifyRequest)
  })
_sym_db.RegisterMessage(NotifyRequest)

NotifyResponse = _reflection.GeneratedProtocolMessageType('NotifyResponse', (_message.Message,), {
  'DESCRIPTOR' : _NOTIFYRESPONSE,
  '__module__' : 'order_pb2'
  # @@protoc_insertion_point(class_scope:NotifyResponse)
  })
_sym_db.RegisterMessage(NotifyResponse)

SyncRequest = _reflection.GeneratedProtocolMessageType('SyncRequest', (_message.Message,), {
  'DESCRIPTOR' : _SYNCREQUEST,
  '__module__' : 'order_pb2'
  # @@protoc_insertion_point(class_scope:SyncRequest)
  })
_sym_db.RegisterMessage(SyncRequest)

SyncResponse = _reflection.GeneratedProtocolMessageType('SyncResponse', (_message.Message,), {
  'DESCRIPTOR' : _SYNCRESPONSE,
  '__module__' : 'order_pb2'
  # @@protoc_insertion_point(class_scope:SyncResponse)
  })
_sym_db.RegisterMessage(SyncResponse)

_ORDER = DESCRIPTOR.services_by_name['Order']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _BUYREQUEST._serialized_start=15
  _BUYREQUEST._serialized_end=84
  _BUYRESPONSE._serialized_start=86
  _BUYRESPONSE._serialized_end=141
  _ORDERQUERYREQUEST._serialized_start=143
  _ORDERQUERYREQUEST._serialized_end=183
  _ORDERQUERYRESPONSE._serialized_start=185
  _ORDERQUERYRESPONSE._serialized_end=308
  _HEALTHCHECKREQUEST._serialized_start=310
  _HEALTHCHECKREQUEST._serialized_end=351
  _HEALTHCHECKRESPONSE._serialized_start=353
  _HEALTHCHECKRESPONSE._serialized_end=391
  _NOTIFYREQUEST._serialized_start=393
  _NOTIFYREQUEST._serialized_end=424
  _NOTIFYRESPONSE._serialized_start=426
  _NOTIFYRESPONSE._serialized_end=460
  _SYNCREQUEST._serialized_start=462
  _SYNCREQUEST._serialized_end=578
  _SYNCRESPONSE._serialized_start=581
  _SYNCRESPONSE._serialized_end=737
  _ORDER._serialized_start=740
  _ORDER._serialized_end=986
# @@protoc_insertion_point(module_scope)
